"""COCO データセットのクラス定義.

プリトレインモデル (RT-DETR) 使用時に class_names / num_classes を
自動設定するために使用する.
HuggingFace RT-DETR は連番 0-79 にリマップ済みのため 80 要素リストで対応する.
"""

COCO_CLASS_NAMES: list[str] = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]
"""COCO 80 クラス名リスト (連番 0-79)."""

COCO_NUM_CLASSES: int = len(COCO_CLASS_NAMES)
"""COCO クラス数 (80)."""

PRETRAINED_CONFIG_PATH: str = "configs/pretrained_rtdetr_coco.py"
"""プリトレインモデル用設定ファイルのパス."""
